services:
  - type: web
    name: dayspring-chapel
    env: docker
    dockerfilePath: dayspring-chapel-nextjs/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: dayspring-chapel-nextjs